"""
Network Performance Anomaly Detection Dashboard
Streamlit Application - Reads outputs from Jupyter Notebook
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import json
import os

# Page config
st.set_page_config(
    page_title="Network Anomaly Detection Dashboard",
    page_icon="📡",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS
st.markdown("""
<style>
    .main-header {
        font-size: 2.5rem;
        font-weight: bold;
        color: #1f77b4;
        text-align: center;
        margin-bottom: 1rem;
    }
    .metric-card {
        background-color: #f0f2f6;
        border-radius: 10px;
        padding: 1rem;
        text-align: center;
    }
    .metric-value {
        font-size: 2rem;
        font-weight: bold;
        color: #1f77b4;
    }
    .metric-label {
        font-size: 0.9rem;
        color: #666;
    }
</style>
""", unsafe_allow_html=True)


@st.cache_data
def load_data():
    """Load all output files generated by the notebook"""
    data = {}
    
    # Main results
    if os.path.exists('outputs/processed_data_with_anomalies.csv'):
        data['main'] = pd.read_csv('outputs/processed_data_with_anomalies.csv')
        data['main']['aggregate_date'] = pd.to_datetime(data['main']['aggregate_date'])
    
    # Summary statistics
    if os.path.exists('outputs/summary_stats.json'):
        with open('outputs/summary_stats.json', 'r') as f:
            data['summary'] = json.load(f)
    
    # Method comparison
    if os.path.exists('outputs/method_comparison.csv'):
        data['comparison'] = pd.read_csv('outputs/method_comparison.csv')
    
    # Q1: Regional variability
    if os.path.exists('outputs/q1_regional_variability.csv'):
        data['q1'] = pd.read_csv('outputs/q1_regional_variability.csv')
    
    # Q2: Daily anomalies
    if os.path.exists('outputs/q2_daily_anomalies.csv'):
        data['q2'] = pd.read_csv('outputs/q2_daily_anomalies.csv')
        data['q2']['aggregate_date'] = pd.to_datetime(data['q2']['aggregate_date'])
    
    # Q3: Carrier consistency
    if os.path.exists('outputs/q3_carrier_consistency.csv'):
        data['q3'] = pd.read_csv('outputs/q3_carrier_consistency.csv')
    
    # Q4: LTE vs 5G
    if os.path.exists('outputs/q4_lte_vs_5g.csv'):
        data['q4'] = pd.read_csv('outputs/q4_lte_vs_5g.csv')
    
    # Q5: Region-carrier combinations
    if os.path.exists('outputs/q5_region_carrier_combinations.csv'):
        data['q5'] = pd.read_csv('outputs/q5_region_carrier_combinations.csv')
    
    # Anomaly log
    if os.path.exists('outputs/anomaly_log.csv'):
        data['anomaly_log'] = pd.read_csv('outputs/anomaly_log.csv')
        data['anomaly_log']['aggregate_date'] = pd.to_datetime(data['anomaly_log']['aggregate_date'])
    
    return data


def main():
    # Load data
    data = load_data()
    
    if not data:
        st.error("No output files found! Please run the Jupyter notebook first.")
        st.code("jupyter nbconvert --execute Network_Anomaly_Detection.ipynb --to notebook")
        return
    
    # Sidebar
    st.sidebar.title("📡 Network Anomaly Detection")
    st.sidebar.markdown("---")
    
    page = st.sidebar.radio(
        "Navigate",
        ["📊 Overview", "🔍 Anomaly Analysis", "📈 Performance Trends", 
         "❓ Project Questions", "📋 Anomaly Log"],
        index=0
    )
    
    st.sidebar.markdown("---")
    
    # Filters in sidebar
    if 'main' in data:
        st.sidebar.subheader("Filters")
        
        # Region filter
        regions = ['All'] + sorted(data['main']['region'].unique().tolist())
        selected_region = st.sidebar.selectbox("Region", regions)
        
        # Carrier filter
        carriers = ['All'] + sorted(data['main']['carrier_name'].unique().tolist())
        selected_carrier = st.sidebar.selectbox("Carrier", carriers)
        
        # Technology filter
        technologies = ['All'] + sorted(data['main']['technology_type'].unique().tolist())
        selected_tech = st.sidebar.selectbox("Technology", technologies)
        
        # Apply filters
        df_filtered = data['main'].copy()
        if selected_region != 'All':
            df_filtered = df_filtered[df_filtered['region'] == selected_region]
        if selected_carrier != 'All':
            df_filtered = df_filtered[df_filtered['carrier_name'] == selected_carrier]
        if selected_tech != 'All':
            df_filtered = df_filtered[df_filtered['technology_type'] == selected_tech]
    
    # Main content based on page
    if page == "📊 Overview":
        show_overview(data, df_filtered)
    elif page == "🔍 Anomaly Analysis":
        show_anomaly_analysis(data, df_filtered)
    elif page == "📈 Performance Trends":
        show_performance_trends(data, df_filtered)
    elif page == "❓ Project Questions":
        show_project_questions(data)
    elif page == "📋 Anomaly Log":
        show_anomaly_log(data, df_filtered)


def show_overview(data, df):
    """Overview page with key metrics"""
    st.markdown('<p class="main-header">Network Performance Anomaly Detection</p>', 
                unsafe_allow_html=True)
    
    st.markdown("---")
    
    # Key metrics
    if 'summary' in data:
        summary = data['summary']
        
        col1, col2, col3, col4 = st.columns(4)
        
        with col1:
            st.metric("Total Records", f"{summary['total_records']:,}")
        
        with col2:
            st.metric("Regions", summary['total_regions'])
        
        with col3:
            st.metric("Carriers", summary['total_carriers'])
        
        with col4:
            st.metric("High-Confidence Anomalies", f"{summary['high_confidence_anomalies']:,}")
        
        st.markdown("---")
        
        col5, col6, col7 = st.columns(3)
        
        with col5:
            st.metric("Avg Download Speed", f"{summary['mean_download_mbps']:.2f} Mbps")
        
        with col6:
            st.metric("Avg Upload Speed", f"{summary['mean_upload_mbps']:.2f} Mbps")
        
        with col7:
            st.metric("Avg Latency", f"{summary['mean_latency_ms']:.2f} ms")
    
    st.markdown("---")
    
    # Method comparison
    if 'comparison' in data:
        st.subheader("Anomaly Detection Methods Comparison")
        
        col1, col2 = st.columns([1, 1])
        
        with col1:
            fig = px.bar(
                data['comparison'],
                x='Method',
                y='Anomalies Detected',
                color='Method',
                title="Anomalies Detected by Each Method",
                color_discrete_sequence=['#1f77b4', '#ff7f0e', '#2ca02c']
            )
            fig.update_layout(showlegend=False)
            st.plotly_chart(fig, use_container_width=True)
        
        with col2:
            # Create pie chart for method agreement
            if 'main' in data:
                agreement_counts = [
                    (df['methods_agree'] == 3).sum(),
                    (df['methods_agree'] == 2).sum(),
                    (df['methods_agree'] == 1).sum(),
                    (df['methods_agree'] == 0).sum()
                ]
                labels = ['All 3 Methods', 'Exactly 2', 'Exactly 1', 'None']
                
                fig = go.Figure(data=[go.Pie(
                    labels=labels,
                    values=agreement_counts,
                    hole=0.4,
                    marker_colors=['#d62728', '#ff7f0e', '#ffbb78', '#2ca02c']
                )])
                fig.update_layout(title="Method Agreement Distribution")
                st.plotly_chart(fig, use_container_width=True)
    
    # Feature space visualization
    st.subheader("Anomaly Distribution in Feature Space")
    
    col1, col2 = st.columns(2)
    
    with col1:
        fig = px.scatter(
            df,
            x=df['mean_download_kbps']/1000,
            y='mean_latency_ms',
            color='high_confidence_anomaly',
            title="Download Speed vs Latency",
            labels={'x': 'Download Speed (Mbps)', 'mean_latency_ms': 'Latency (ms)'},
            color_discrete_map={0: '#1f77b4', 1: '#d62728'},
            opacity=0.6
        )
        fig.update_traces(marker=dict(size=5))
        st.plotly_chart(fig, use_container_width=True)
    
    with col2:
        fig = px.scatter(
            df,
            x=df['mean_upload_kbps']/1000,
            y='mean_latency_ms',
            color='high_confidence_anomaly',
            title="Upload Speed vs Latency",
            labels={'x': 'Upload Speed (Mbps)', 'mean_latency_ms': 'Latency (ms)'},
            color_discrete_map={0: '#1f77b4', 1: '#d62728'},
            opacity=0.6
        )
        fig.update_traces(marker=dict(size=5))
        st.plotly_chart(fig, use_container_width=True)


def show_anomaly_analysis(data, df):
    """Detailed anomaly analysis page"""
    st.title("🔍 Anomaly Analysis")
    
    # Anomalies by region
    st.subheader("Anomalies by Region")
    
    region_anomalies = df.groupby('region').agg({
        'high_confidence_anomaly': 'sum',
        'iso_anomaly': 'sum',
        'ocsvm_anomaly': 'sum',
        'ae_anomaly': 'sum'
    }).reset_index()
    region_anomalies = region_anomalies.sort_values('high_confidence_anomaly', ascending=True)
    
    fig = go.Figure()
    fig.add_trace(go.Bar(
        y=region_anomalies['region'],
        x=region_anomalies['high_confidence_anomaly'],
        orientation='h',
        name='High-Confidence Anomalies',
        marker_color='#d62728'
    ))
    fig.update_layout(
        title="High-Confidence Anomalies by Region",
        xaxis_title="Number of Anomalies",
        yaxis_title="Region",
        height=500
    )
    st.plotly_chart(fig, use_container_width=True)
    
    # Anomalies by carrier
    st.subheader("Anomalies by Carrier")
    
    col1, col2 = st.columns(2)
    
    with col1:
        carrier_data = df.groupby('carrier_name').agg({
            'high_confidence_anomaly': ['sum', 'mean'],
            'iso_anomaly': 'sum',
            'ocsvm_anomaly': 'sum',
            'ae_anomaly': 'sum'
        }).reset_index()
        carrier_data.columns = ['Carrier', 'Total Anomalies', 'Anomaly Rate', 
                                'Isolation Forest', 'OC-SVM', 'Autoencoder']
        carrier_data['Anomaly Rate'] = carrier_data['Anomaly Rate'] * 100
        
        fig = px.bar(
            carrier_data,
            x='Carrier',
            y=['Isolation Forest', 'OC-SVM', 'Autoencoder'],
            title="Anomalies by Method per Carrier",
            barmode='group',
            color_discrete_sequence=['#1f77b4', '#ff7f0e', '#2ca02c']
        )
        st.plotly_chart(fig, use_container_width=True)
    
    with col2:
        fig = px.bar(
            carrier_data,
            x='Carrier',
            y='Anomaly Rate',
            title="Anomaly Rate by Carrier (%)",
            color='Carrier',
            color_discrete_sequence=['#1f77b4', '#ff7f0e', '#2ca02c']
        )
        st.plotly_chart(fig, use_container_width=True)
    
    # Anomalies by technology
    st.subheader("Anomalies by Technology")
    
    tech_data = df.groupby('technology_type').agg({
        'high_confidence_anomaly': ['sum', 'mean', 'count'],
        'mean_download_kbps': 'mean',
        'mean_latency_ms': 'mean'
    }).reset_index()
    tech_data.columns = ['Technology', 'Anomalies', 'Anomaly Rate', 'Total Records',
                         'Avg Download', 'Avg Latency']
    tech_data['Anomaly Rate'] = tech_data['Anomaly Rate'] * 100
    tech_data['Avg Download'] = tech_data['Avg Download'] / 1000
    
    col1, col2 = st.columns(2)
    
    with col1:
        fig = px.bar(
            tech_data,
            x='Technology',
            y='Anomaly Rate',
            title="Anomaly Rate by Technology (%)",
            color='Technology',
            color_discrete_sequence=['#1f77b4', '#2ca02c']
        )
        st.plotly_chart(fig, use_container_width=True)
    
    with col2:
        fig = px.bar(
            tech_data,
            x='Technology',
            y='Avg Download',
            title="Average Download Speed by Technology (Mbps)",
            color='Technology',
            color_discrete_sequence=['#1f77b4', '#2ca02c']
        )
        st.plotly_chart(fig, use_container_width=True)


def show_performance_trends(data, df):
    """Performance trends over time"""
    st.title("📈 Performance Trends")
    
    # Daily trends
    st.subheader("Daily Performance Metrics")
    
    daily_data = df.groupby('aggregate_date').agg({
        'mean_download_kbps': 'mean',
        'mean_upload_kbps': 'mean',
        'mean_latency_ms': 'mean',
        'high_confidence_anomaly': 'sum'
    }).reset_index()
    
    fig = make_subplots(
        rows=3, cols=1,
        subplot_titles=('Download Speed', 'Upload Speed', 'Latency'),
        vertical_spacing=0.1
    )
    
    fig.add_trace(
        go.Scatter(x=daily_data['aggregate_date'], 
                   y=daily_data['mean_download_kbps']/1000,
                   mode='lines', name='Download (Mbps)',
                   line=dict(color='#1f77b4')),
        row=1, col=1
    )
    
    fig.add_trace(
        go.Scatter(x=daily_data['aggregate_date'], 
                   y=daily_data['mean_upload_kbps']/1000,
                   mode='lines', name='Upload (Mbps)',
                   line=dict(color='#ff7f0e')),
        row=2, col=1
    )
    
    fig.add_trace(
        go.Scatter(x=daily_data['aggregate_date'], 
                   y=daily_data['mean_latency_ms'],
                   mode='lines', name='Latency (ms)',
                   line=dict(color='#d62728')),
        row=3, col=1
    )
    
    fig.update_layout(height=700, showlegend=True, title_text="Daily Performance Trends")
    fig.update_xaxes(title_text="Date", row=3, col=1)
    fig.update_yaxes(title_text="Mbps", row=1, col=1)
    fig.update_yaxes(title_text="Mbps", row=2, col=1)
    fig.update_yaxes(title_text="ms", row=3, col=1)
    
    st.plotly_chart(fig, use_container_width=True)
    
    # Daily anomalies
    st.subheader("Daily Anomaly Count")
    
    fig = px.bar(
        daily_data,
        x='aggregate_date',
        y='high_confidence_anomaly',
        title="High-Confidence Anomalies per Day",
        labels={'aggregate_date': 'Date', 'high_confidence_anomaly': 'Anomaly Count'},
        color_discrete_sequence=['#d62728']
    )
    st.plotly_chart(fig, use_container_width=True)
    
    # KPI distributions
    st.subheader("KPI Distributions")
    
    col1, col2, col3 = st.columns(3)
    
    with col1:
        fig = px.histogram(
            df, x=df['mean_download_kbps']/1000,
            title="Download Speed Distribution",
            labels={'x': 'Download Speed (Mbps)'},
            nbins=50,
            color_discrete_sequence=['#1f77b4']
        )
        st.plotly_chart(fig, use_container_width=True)
    
    with col2:
        fig = px.histogram(
            df, x=df['mean_upload_kbps']/1000,
            title="Upload Speed Distribution",
            labels={'x': 'Upload Speed (Mbps)'},
            nbins=50,
            color_discrete_sequence=['#ff7f0e']
        )
        st.plotly_chart(fig, use_container_width=True)
    
    with col3:
        fig = px.histogram(
            df, x='mean_latency_ms',
            title="Latency Distribution",
            labels={'mean_latency_ms': 'Latency (ms)'},
            nbins=50,
            color_discrete_sequence=['#d62728']
        )
        st.plotly_chart(fig, use_container_width=True)


def show_project_questions(data):
    """Display answers to project questions"""
    st.title("❓ Project Questions & Answers")
    
    # Q1
    st.subheader("Q1: Which regions show the most variable download speed?")
    
    if 'q1' in data:
        q1_data = data['q1'].head(10)
        
        col1, col2 = st.columns([1, 1])
        
        with col1:
            fig = px.bar(
                q1_data.sort_values('cv', ascending=True),
                x='cv',
                y='region',
                orientation='h',
                title="Download Speed Variability (Coefficient of Variation)",
                labels={'cv': 'CV (%)', 'region': 'Region'},
                color='cv',
                color_continuous_scale='Reds'
            )
            st.plotly_chart(fig, use_container_width=True)
        
        with col2:
            st.dataframe(q1_data[['region', 'mean_download', 'std_download', 'cv']], 
                        use_container_width=True)
    
    st.markdown("---")
    
    # Q2
    st.subheader("Q2: Which specific days show abnormal network behavior?")
    
    if 'q2' in data:
        q2_data = data['q2'].head(10)
        
        fig = px.bar(
            data['q2'].sort_values('aggregate_date'),
            x='aggregate_date',
            y='high_confidence_anomaly',
            title="Daily High-Confidence Anomaly Count",
            labels={'aggregate_date': 'Date', 'high_confidence_anomaly': 'Anomalies'},
            color_discrete_sequence=['#9467bd']
        )
        st.plotly_chart(fig, use_container_width=True)
        
        st.markdown("**Top 10 Days with Most Anomalies:**")
        st.dataframe(q2_data[['aggregate_date', 'high_confidence_anomaly', 
                              'mean_download_kbps', 'mean_latency_ms']], 
                    use_container_width=True)
    
    st.markdown("---")
    
    # Q3
    st.subheader("Q3: Which carrier shows the most consistent performance?")
    
    if 'q3' in data:
        q3_data = data['q3']
        
        col1, col2 = st.columns(2)
        
        with col1:
            fig = px.bar(
                q3_data,
                x='carrier_name',
                y='download_cv',
                title="Download Speed Consistency by Carrier (Lower = More Consistent)",
                labels={'carrier_name': 'Carrier', 'download_cv': 'CV (%)'},
                color='carrier_name',
                color_discrete_sequence=['#1f77b4', '#ff7f0e', '#2ca02c']
            )
            st.plotly_chart(fig, use_container_width=True)
        
        with col2:
            fig = px.bar(
                q3_data,
                x='carrier_name',
                y='anomaly_rate',
                title="Anomaly Rate by Carrier (%)",
                labels={'carrier_name': 'Carrier', 'anomaly_rate': 'Anomaly Rate (%)'},
                color='carrier_name',
                color_discrete_sequence=['#1f77b4', '#ff7f0e', '#2ca02c']
            )
            st.plotly_chart(fig, use_container_width=True)
    
    st.markdown("---")
    
    # Q4
    st.subheader("Q4: Does LTE vs 5G show different anomaly patterns?")
    
    if 'q4' in data:
        q4_data = data['q4']
        
        col1, col2 = st.columns(2)
        
        with col1:
            fig = px.bar(
                q4_data,
                x='technology_type',
                y='anomaly_rate',
                title="Anomaly Rate by Technology (%)",
                labels={'technology_type': 'Technology', 'anomaly_rate': 'Anomaly Rate (%)'},
                color='technology_type',
                color_discrete_sequence=['#1f77b4', '#2ca02c']
            )
            st.plotly_chart(fig, use_container_width=True)
        
        with col2:
            fig = go.Figure()
            fig.add_trace(go.Bar(
                name='Download Speed',
                x=q4_data['technology_type'],
                y=q4_data['mean_download_kbps_mean']/1000,
                marker_color='#1f77b4'
            ))
            fig.update_layout(
                title="Average Download Speed by Technology (Mbps)",
                xaxis_title="Technology",
                yaxis_title="Mbps"
            )
            st.plotly_chart(fig, use_container_width=True)
    
    st.markdown("---")
    
    # Q5
    st.subheader("Q5: Top 5 worst performing region-carrier combinations")
    
    if 'q5' in data:
        q5_data = data['q5'].head(5)
        
        q5_data['combination'] = q5_data['region'] + ' - ' + q5_data['carrier_name']
        
        fig = px.bar(
            q5_data,
            x='high_confidence_anomaly_sum',
            y='combination',
            orientation='h',
            title="Top 5 Worst Region-Carrier Combinations",
            labels={'high_confidence_anomaly_sum': 'High-Confidence Anomalies', 
                    'combination': 'Region - Carrier'},
            color='high_confidence_anomaly_sum',
            color_continuous_scale='Reds'
        )
        fig.update_layout(yaxis={'categoryorder': 'total ascending'})
        st.plotly_chart(fig, use_container_width=True)


def show_anomaly_log(data, df):
    """Show the anomaly log"""
    st.title("📋 Anomaly Log")
    
    st.markdown("""
    This table shows all **high-confidence anomalies** detected by at least 2 methods.
    """)
    
    if 'anomaly_log' in data:
        anomaly_df = data['anomaly_log']
        
        # Filter based on sidebar selection
        if 'region' in st.session_state and st.session_state.get('region') != 'All':
            anomaly_df = anomaly_df[anomaly_df['region'] == st.session_state['region']]
        if 'carrier_name' in st.session_state and st.session_state.get('carrier') != 'All':
            anomaly_df = anomaly_df[anomaly_df['carrier_name'] == st.session_state['carrier']]
        
        # Date range filter
        st.subheader("Filter by Date Range")
        col1, col2 = st.columns(2)
        
        min_date = anomaly_df['aggregate_date'].min()
        max_date = anomaly_df['aggregate_date'].max()
        
        with col1:
            start_date = st.date_input("Start Date", min_date)
        with col2:
            end_date = st.date_input("End Date", max_date)
        
        mask = (anomaly_df['aggregate_date'].dt.date >= start_date) & \
               (anomaly_df['aggregate_date'].dt.date <= end_date)
        anomaly_df = anomaly_df[mask]
        
        # Show statistics
        st.subheader("Summary")
        col1, col2, col3 = st.columns(3)
        
        with col1:
            st.metric("Total Anomalies", len(anomaly_df))
        
        with col2:
            if len(anomaly_df) > 0:
                st.metric("Affected Regions", anomaly_df['region'].nunique())
            else:
                st.metric("Affected Regions", 0)
        
        with col3:
            if len(anomaly_df) > 0:
                st.metric("Date Range", f"{(max_date - min_date).days} days")
            else:
                st.metric("Date Range", "N/A")
        
        # Show table
        st.subheader("Anomaly Records")
        
        # Format columns for display
        display_df = anomaly_df.copy()
        display_df['aggregate_date'] = display_df['aggregate_date'].dt.strftime('%Y-%m-%d')
        display_df['mean_download_kbps'] = (display_df['mean_download_kbps'] / 1000).round(2).astype(str) + ' Mbps'
        display_df['mean_upload_kbps'] = (display_df['mean_upload_kbps'] / 1000).round(2).astype(str) + ' Mbps'
        display_df['mean_latency_ms'] = display_df['mean_latency_ms'].round(2).astype(str) + ' ms'
        
        # Rename columns for clarity
        display_df = display_df.rename(columns={
            'aggregate_date': 'Date',
            'region': 'Region',
            'carrier_name': 'Carrier',
            'technology_type': 'Technology',
            'mean_download_kbps': 'Download',
            'mean_upload_kbps': 'Upload',
            'mean_latency_ms': 'Latency',
            'iso_anomaly': 'Isolation Forest',
            'ocsvm_anomaly': 'OC-SVM',
            'ae_anomaly': 'Autoencoder',
            'methods_agree': 'Methods Agreeing'
        })
        
        st.dataframe(
            display_df,
            use_container_width=True,
            height=400
        )
        
        # Download button
        csv = anomaly_df.to_csv(index=False)
        st.download_button(
            label="Download Anomaly Log (CSV)",
            data=csv,
            file_name="anomaly_log.csv",
            mime="text/csv"
        )
    else:
        st.info("No anomaly log data available. Please run the notebook first.")


if __name__ == "__main__":
    main()
